version: '3'

services:
  nginx:
    build:
      context: .
    volumes:
      - type: bind
        source: ./docker/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    tty: true
